"<!DOCTYPE html>"
"<html lang=\"en\">"
""
"  <head>"
"    <meta charset=\"utf-8\">"
"    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
"    <title>Control Agua Caliente Ombu 880</title>"
"    <meta name=\"description\" content=\"Control de agua caliente\">"
"    <meta name=\"author\" content=\"Joacofz6\">"
"    <!-- <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\"> -->"
"    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">"
"    <link href=\"css/style.css\" rel=\"stylesheet\">"
"    <style>"
"      .switch {"
"        position: relative;"
"        display: inline-block;"
"        width: 60px;"
"        height: 34px;"
"      }"
""
"      .switch input {"
"        opacity: 0;"
"        width: 0;"
"        height: 0;"
"      }"
""
"      .slider {"
"        position: absolute;"
"        cursor: pointer;"
"        top: 0;"
"        left: 0;"
"        right: 0;"
"        bottom: 0;"
"        background-color: #ccc;"
"        -webkit-transition: .4s;"
"        transition: .4s;"
"      }"
""
"      .slider:before {"
"        position: absolute;"
"        content: \"\";"
"        height: 26px;"
"        width: 26px;"
"        left: 4px;"
"        bottom: 4px;"
"        background-color: white;"
"        -webkit-transition: .4s;"
"        transition: .4s;"
"      }"
""
"      input:checked+.slider {"
"        background-color: #2196F3;"
"      }"
""
"      input:focus+.slider {"
"        box-shadow: 0 0 1px #2196F3;"
"      }"
""
"      input:checked+.slider:before {"
"        -webkit-transform: translateX(26px);"
"        -ms-transform: translateX(26px);"
"        transform: translateX(26px);"
"      }"
""
"      /* Rounded sliders */"
"      .slider.round {"
"        border-radius: 34px;"
"      }"
""
"      .slider.round:before {"
"        border-radius: 50%;"
"      }"
""
"    </style>"
"  </head>"
""
"  <body>"
"    <div class=\"container-fluid\">"
"      <div class=\"row\">"
"        <div class=\"col-md-12\">"
"          <div class=\"jumbotron\">"
"            <h2> Control del Agua Caliente </h2>"
"            <p> Ya era hora de bañarse, no?. </p>"
"          </div>"
"          <img alt=\"Bootstrap Media Another Preview\" src=\"https://previews.123rf.com/images/alfadanz/alfadanz1807/alfadanz180700040/103920983-yellow-rubber-duck-cartoon-cute-ducky-for-bath-duckling-with-diving-mask-and-snorkel-flat-vector-ill.jpg\""
"            style=\"max-width: 100px;\">"
"          <h4> Temperatura calef&oacute;n: <span id=\"tempCalefon\" class=\"label label-warning\">DOS</span></h4>"
"          <!-- <h4 id=\"tempCalefon\"> DOS</h4> -->"
""
""
"          <div class=\"btn-group\" role=\"group\">"
"            <button class=\"btn btn-success minimo\" type=\"button\"> Minimo </button>"
"            <button class=\"btn btn-warning dos\" type=\"button\"> DOS </button>"
"            <button class=\"btn btn-warning tres\" type=\"button\"> TRES </button>"
"            <button class=\"btn btn-danger maximo\" type=\"button\"> M&aacute;ximo </button>"
"          </div>"
"        </div>"
"      </div>"
"      <div class=\"row\">"
"        <div class=\"col-md-12\">"
"          <h3> Control de la bomba, luz y extractor. </h3>"
"          <div class=\"row\">"
"            <div class=\"col-md-4\">"
"              <h4> Bomba </h4>"
"              <label class=\"switch\">"
"                <input id=\"bomba\" type=\"checkbox\">"
"                <span class=\"slider round\"></span>"
"              </label>"
"              <span id=\"bombaStatus\" class=\"badge badge-info\">Apagada</span>"
"            </div>"
"            <div class=\"col-md-4\">"
"              <h4> Luz </h4>"
"              <label class=\"switch\">"
"                <input id=\"luz\" type=\"checkbox\">"
"                <span class=\"slider round\"></span>"
"              </label>"
"              <span id=\"luzStatus\" class=\"badge badge-info\">Apagada</span>"
"            </div>"
"            <div class=\"col-md-4\">"
"              <h4> Extractor </h4>"
"              <label class=\"switch\">"
"                <input id=\"extractor\" type=\"checkbox\">"
"                <span class=\"slider round\"></span>"
"              </label>"
"              <span id=\"extractorStatus\" class=\"badge badge-info\">Apagado</span>"
"            </div>"
"          </div>"
"        </div>"
"      </div>"
"      <div class=\"row\">"
"        <div class=\"col-md-12\">"
"          <div class=\"row\">"
"            <div class=\"col-md-4\">"
"              <span id=\"bombaMinRest\" class=\"badge badge-info\">Bomba xxx minutos restantes</span>"
"            </div>"
"            <div class=\"col-md-4\">"
"              <span id=\"luzMinRest\" class=\"badge badge-info\">luz xxx minutos restantes</span>"
"            </div>"
"            <div class=\"col-md-4\">"
"              <span id=\"extractorMinRest\" class=\"badge badge-info\">extractor xxx minutos restantes</span>"
"            </div>"
"          </div>"
"        </div>"
"      </div>"
"    </div>"
"    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>"
"    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>"
"    <script>"
"      // bomba start"
"      $(\"#bomba\").click(function(e) {"
"        if ($(this).is(':checked')) {"
"          $(\"#bombaStatus\").text(\"Encendida\")"
"        } else {"
"          $(\"#bombaStatus\").text(\"Apagada\")"
"          $(\"#bombaMinRest\").hide()"
"        }"
"      });"
""
"      function setBomba(time) {"
"        if (time > 0) {"
"          $(\"#bomba\").prop('checked', true);"
"          $(\"#bombaStatus\").text(\"Encendida\")"
"          $(\"#bombaMinRest\").text(time / 60000 + \" minutos restantes.\")"
"          $(\"#bombaMinRest\").show()"
"        } else {"
"          $(\"#bomba\").prop('checked', false);"
"          $(\"#bombaStatus\").text(\"Apagada\")"
"          $(\"#bombaMinRest\").hide()"
"        }"
"      }"
"      ///bomba end"
"      $(\"#luz\").click(function(e) {"
"        if ($(this).is(':checked')) {"
"          $(\"#luzStatus\").text(\"Encendida\")"
"        } else {"
"          $(\"#luzStatus\").text(\"Apagada\")"
"          $(\"#luzMinRest\").hide()"
"        }"
"      });"
""
"      function setLuz(time) {"
"        if (time > 0) {"
"          $(\"#luz\").prop('checked', true);"
"          $(\"#luzStatus\").text(\"Encendida\")"
"          $(\"#luzMinRest\").text(time / 60000 + \" minutos restantes.\")"
"          $(\"#luzMinRest\").show()"
"        } else {"
"          $(\"#luz\").prop('checked', false);"
"          $(\"#luzStatus\").text(\"Apagada\")"
"          $(\"#luzMinRest\").hide()"
"        }"
"      }"
"      ///luz end"
"      $(\"#extractor\").click(function(e) {"
"        if ($(this).is(':checked')) {"
"          $(\"#extractorStatus\").text(\"Encendido\")"
"        } else {"
"          $(\"#extractorStatus\").text(\"Apagado\")"
"          $(\"#extractorMinRest\").hide()"
"        }"
"      });"
""
"      function setExtractor(time) {"
"        if (time > 0) {"
"          $(\"#extractor\").prop('checked', true);"
"          $(\"#extractorStatus\").text(\"Encendido\")"
"          $(\"#extractorMinRest\").text(time / 60000 + \" minutos restantes.\")"
"          $(\"#extractorMinRest\").show()"
"        } else {"
"          $(\"#extractor\").prop('checked', false);"
"          $(\"#extractorStatus\").text(\"Apagado\")"
"          $(\"#extractorMinRest\").hide()"
"        }"
"      }"
"      //end extracotor"
"      function setTempCalefon(temp) {"
"        removeClass()"
"        switch (temp) {"
"          case 1:"
"            $(\"#tempCalefon\").text('MINIMO');"
"            $(\"#tempCalefon\").addClass('label-success');"
"            break;"
"          case 2:"
"            $(\"#tempCalefon\").text('DOS');"
"            $(\"#tempCalefon\").addClass('label-warning');"
"            break;"
"          case 3:"
"            $(\"#tempCalefon\").text('TRES');"
"            $(\"#tempCalefon\").addClass('label-warning');"
"            break;"
"          case 4:"
"            $(\"#tempCalefon\").text('MAXIMO');"
"            $(\"#tempCalefon\").addClass('label-danger');"
"            break;"
"        }"
"        setClass(temp);"
"      }"
"$('.minimo').click(function(e) {"
"  setTempCalefon(1);"
"  removeClass()"
"});"
"$('.dos').click(function(e) {"
"  setTempCalefon(2);"
"  removeClass()"
"});"
"$('.tres').click(function(e) {"
"  setTempCalefon(3);"
"  removeClass()"
"});"
""
"$('.maximo').click(function(e) {"
"  setTempCalefon(4);"
"  removeClass()"
"});"
""
"function removeClass(){"
"  $(\"#tempCalefon\").removeClass('label-info');"
"  $(\"#tempCalefon\").removeClass('label-warning');"
"  $(\"#tempCalefon\").removeClass('label-danger');"
"}"
""
""
"      jQuery(document).ready(function() {"
"        setBomba(0);"
"        setLuz(0);"
"        setExtractor(0);"
"        setTempCalefon(3);"
"      });"
""
"    </script>"
"    <!-- <script src=\"js/scripts.js\"></script> -->"
"  </body>"
""
"</html>"
"